GoogleDocFormats = {0: ("HTML", "text/html"),
                    1: ("HTML (zipped)", "application/zip"),
                    2: ("Plain text", "text/plain"),
                    3: ("Rich text", "application/rtf"),
                    4: ("Open Office doc", "application/vnd.oasis.opendocument.text"),
                    5: ("PDF", "application/pdf"),
                    6: ("MS Word document", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
                    7: ("EPUB", "application/epub+zip"),
                    8: ("MS Excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
                    9: ("Open Office sheet", "application/x-vnd.oasis.opendocument.spreadsheet"),
                    10: ("CSV first sheet only", "text/csv"),
                    11: ("TSV (first sheet only)", "text/tab-separated-values"),
                    12: ("JPEG", "image/jpeg"),
                    13: ("PNG", "image/png"),
                    14: ("SVG", "image/svg+xml"),
                    15: ("MS PowerPoint", "application/vnd.openxmlformats-officedocument.presentationml.presentation"),
                    16: ("Open Office presentation", "application/vnd.oasis.opendocument.presentation"),
                    17: ("JSON", "application / vnd.google - apps.script + json")}

